FROM python:3.9.2-slim-buster

WORKDIR /app

LABEL maintainer="github.com/fc-anjos"
LABEL description="Development image for a GeoDjango starter"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update  \
    && apt-get -y install netcat gcc postgresql \
    && apt-get clean

RUN apt-get update \
    && apt-get -y binutils libproj-dev gdal-bin python-gdal pyhon3-gdal \
    && apt-get clean

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app